export const LOCATIONS_SET = 'LOCATIONS_SET';
export const SCHEDULES_SET = 'SCHEDULES_SET';
export const MY_FLIGHT_SET = 'MY_FLIGHT_SET';
export const ARRIVAL_WEATHER_SET = 'ARRIVAL_WEATHER_SET';
export const PRED_RESULT_SET = 'PRED_RESULT_SET';